Search post
aldaitzwild/DevelopLyon pull request #5
Opened 2021-10-31 11:01 UTC by jcriotte

Delivery of the US search post with key words

2021-11-02 09:16 UTC, aldaitzwild requested changes
Quality code problems : 

FILE: src/Model/PostManager.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 25 | ERROR | [x] Expected 1 newline at end of file; 0 found
 25 | ERROR | [x] The closing brace for the class must go on the next
    |       |     line after the body
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: src/Controller/PostController.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 21 | ERROR | [x] Blank line found at start of control structure
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

2021-11-03 09:16 UTC, jcriotte commented
Delivery correction search bug

2021-11-04 08:42 UTC, aldaitzwild requested changes

2021-11-04 08:42 UTC, aldaitzwild commented on src/Controller/PostController.php
> +            $search = "%" . $searchInput['maRecherche'] . "%";
No, you do this to use the LIKE in SQL. So this should be done in the Manager Not in the Controller.

2021-11-04 09:12 UTC, jcriotte commented on src/Controller/PostController.php
> +            $search = "%" . $searchInput['maRecherche'] . "%";
You just want me not to put the % up to that level because it’s SQL?

2021-11-04 09:28 UTC, jcriotte commented
I modify the search function and searchManager

2021-11-04 09:47 UTC, aldaitzwild commented on src/Controller/PostController.php
> +            $search = "%" . $searchInput['maRecherche'] . "%";
Yes.
Because if you do that in the controller, everybody who will use the search function of your manager will have to do that.
If you do that in your controller it will be done once and for all

2021-11-04 09:47 UTC, aldaitzwild approved these changes

2021-11-04 09:49 UTC, aldaitzwild requested changes
Every thing is good BUT you have a conflicts with the dev branch.
So you to merge the dev into your branch, resolve conflicts, then push it update the PR

2021-11-04 10:51 UTC, jcriotte commented
I did the merge with the dev branch

2021-11-04 10:53 UTC, aldaitzwild approved these changes

2021-11-04 10:53 UTC, merged