Suggestfunction
aldaitzwild/DevelopLyon pull request #8
Opened 2021-11-04 17:24 UTC by jcriotte

Delivery suggestion function after merge with dev

2021-11-05 07:59 UTC, aldaitzwild requested changes

2021-11-05 07:59 UTC, aldaitzwild commented on src/Controller/PostController.php
> +                    $search = new SearchManager();
Why do you use a second searchManager ??? you already have one at this point (look line 72)

2021-11-05 07:59 UTC, aldaitzwild commented on src/Controller/PostController.php
> +                $search = new SearchManager();
And a third one ???

2021-11-05 09:09 UTC, jcriotte commented
PostController Fix Delivery and Layout Change Following Regression

2021-11-07 18:34 UTC, aldaitzwild requested changes

2021-11-07 18:34 UTC, aldaitzwild commented on src/Controller/PostController.php
> +            $search = new SearchManager();
Still the same problem ... Why do you instanciate a second SearchManager() ? There is no mean for that

2021-11-08 10:16 UTC, aldaitzwild requested changes

2021-11-08 10:16 UTC, aldaitzwild commented on src/Controller/PostController.php
> +use function Amp\Internal\getCurrentTime;
What is this use ?? You doesn't seems to use it

2021-11-08 10:36 UTC, jcriotte commented
Delivery PostController with out this line.

2021-11-08 10:47 UTC, aldaitzwild approved these changes

2021-11-08 10:47 UTC, merged